sonar.projectKey=raabshoes
sonar.projectName=RaabShoes

sonar.sources=app,routes,config,database
sonar.tests=tests

sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/**

sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=junit.xml

sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
